from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
REPORTS_DIR = ROOT / "reports"
MODELS_DIR = ROOT / "models"

RANDOM_STATE = 42
TARGET_COLUMN = "bad_review"
MODEL_DATASET = PROCESSED_DIR / "order_risk_modeling.csv"
PRE_DELIVERY_DATASET = PROCESSED_DIR / "order_risk_pre_delivery.csv"
POST_DELIVERY_DATASET = PROCESSED_DIR / "order_risk_post_delivery.csv"
BASELINE_RESULTS = REPORTS_DIR / "baseline_model_results.csv"
TUNED_RESULTS = REPORTS_DIR / "tuned_model_results.csv"
THRESHOLD_RESULTS = REPORTS_DIR / "threshold_analysis.csv"
FEATURE_IMPORTANCE_RESULTS = REPORTS_DIR / "feature_importance.csv"
BEST_MODEL_PATH = MODELS_DIR / "best_order_risk_model.joblib"
ADVANCED_RESULTS = REPORTS_DIR / "advanced_model_results.csv"
ADVANCED_THRESHOLD_RESULTS = REPORTS_DIR / "advanced_threshold_analysis.csv"
CALIBRATION_RESULTS = REPORTS_DIR / "calibration_results.csv"
ADVANCED_BEST_MODEL_PATH = MODELS_DIR / "advanced_best_order_risk_model.joblib"
ERROR_ANALYSIS_DIR = REPORTS_DIR / "error_analysis"
SHAP_IMPORTANCE_RESULTS = REPORTS_DIR / "shap_feature_importance.csv"
TEMPORAL_DATASET = PROCESSED_DIR / "order_risk_temporal.csv"
TIME_VALIDATION_RESULTS = REPORTS_DIR / "time_validation_results.csv"
CV_TUNING_RESULTS = REPORTS_DIR / "cv_tuning_results.csv"
LEARNING_CURVE_RESULTS = REPORTS_DIR / "learning_curve_results.csv"
CV_BEST_MODEL_PATH = MODELS_DIR / "cv_tuned_lightgbm_model.joblib"
DATA_QUALITY_REPORT = REPORTS_DIR / "data_quality_report.md"
DATA_QUALITY_MISSING_VALUES = REPORTS_DIR / "data_quality_missing_values.csv"
BUSINESS_THRESHOLD_RESULTS = REPORTS_DIR / "business_threshold_analysis.csv"
BUSINESS_THRESHOLD_SUMMARY = REPORTS_DIR / "business_threshold_summary.md"
SCORED_ORDERS = REPORTS_DIR / "scored_orders.csv"
HIGH_RISK_ORDERS_SAMPLE = REPORTS_DIR / "high_risk_orders_sample.csv"
MODEL_CARD = REPORTS_DIR / "MODEL_CARD.md"
PRECISION_POLICY_RESULTS = REPORTS_DIR / "precision_policy_results.csv"
PRECISION_POLICY_SUMMARY = REPORTS_DIR / "precision_policy_summary.md"
PRECISION_FOCUSED_MODEL_PATH = MODELS_DIR / "precision_focused_lightgbm_model.joblib"
CRITICAL_RISK_MODEL_PATH = MODELS_DIR / "critical_risk_lightgbm_model.joblib"
